// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Keys;

public class SongsuchenTestCleanUp {
    private WebDriver driver;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void songsuchen() {
        driver.get("http://localhost:8080/");
        driver.findElement(By.cssSelector("input")).sendKeys("she\'s");
        driver.findElement(By.cssSelector("input")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".cyan:nth-child(4) > .btn__content")).click();
    }
}
