// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

public class CreateSong_CleanedUpTest {
    private WebDriver driver;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void createSong() {
        driver.get("http://localhost:8080/");
        driver.findElement(By.cssSelector("#add-song > .btn__content")).click();
        driver.findElement(By.id("sngTitle")).sendKeys("Nevermind");
        driver.findElement(By.id("sngArtist")).sendKeys("Nirvana");
        driver.findElement(By.id("sngGenre")).sendKeys("Alternative Rock");
        driver.findElement(By.id("sngAlbum")).sendKeys("Nevermind");
        driver.findElement(By.id("sngAlbumImg")).sendKeys("https://is3-ssl.mzstatic.com/image/thumb/Features/d0/cc/62/dj.nanioukp.jpg/268x0w.jpg");
        driver.findElement(By.id("sngYoutube")).sendKeys("m-ofL_3EZyE");
        driver.findElement(By.id("sngTab")).sendKeys("-");
        driver.findElement(By.id("sngLyrics")).sendKeys("-");
        driver.findElement(By.cssSelector(".flex > #sngBtn > .btn__content")).click();
    }
}
